version: "3.4"

services:
  client:
    image: autch_server_simple_client:latest
    container_name: client
    ports:
      - 5000:5000
    #networks:
    #  - test
    build:
      context: ./Client
      dockerfile: Dockerfile
    restart: always

  autch_server:
    image: autch_server_simple:latest
    container_name: autch_server
    ports:
      - 5001:5001
    #networks:
    #  - test
    build:
      context: ./Autch_server
      dockerfile: Dockerfile
    restart: always

#networks:
#  test:
#    driver: bridge
